version: '3.8'

services:
  database:
    build: ./DB
    container_name: bpo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: BPO
    ports:
      - "5432:5432"
    volumes:
      - ./DB/BPO.sql:/docker-entrypoint-initdb.d/BPO.sql
    networks:
      - bpo_network

  backend:
    build: ./backend
    container_name: bpo_backend
    ports:
      - "8000:8000"
    env_file:
      - ./DB/.env
    depends_on:
      - database
    networks:
      - bpo_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bpo_frontend 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - bpo_network

networks:
  bpo_network:
    driver: bridge
