services:
    
  backend:
    build: ./backend
    container_name: bpo_backend
    ports:
      - "8000:8000"
    env_file:
      - ./DB/.env
    networks:
      - bpo_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bpo_frontend 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - bpo_network

networks:
  bpo_network:
    driver: bridge
