services:
    
  database:
    build: ./database
    container_name: bpo_database
    ports:
      - "5000:5000"
    env_file:
      - database/.env
    networks:
      - bpo_network


  backend:
    build: ./backend
    container_name: bpo_backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=http://database:5000
    networks:
      - bpo_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bpo_frontend 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - bpo_network

networks:
  bpo_network:
    driver: bridge
